### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Bdabrowsky** [PTR-projects/PTR_mega_firmware#18]
- [x] Integrate preferences with **Web_driver** -> changing password
- [x]  Integrate preferences with **FlightStateDectector** -> change hardcoded values to those from config after sanity check
- [x] Integrate preferences with **Lora_driver** -> changing frequency and mode
- [ ] Complete **FlightStateDetector** component documentation
- [ ] Complete **MMC5983MA_driver** component documentation
- [ ] Complete **Preferences** component documentation
- [ ] Complete **Sensors** component documentation
- [ ] Create **SimpleFs** component documentation
- [ ] Create **SPI_driver** component documentation
- [ ] Redo **Storage_driver** component documentation
- [ ] Complete **SysMgr** component documentation
- [ ] Complete **Web_driver** component documentation
- [x] Add units and data format to all documented values, for example acceleration [m/s^2]
- [ ] #23
- [ ] #24
- [ ] Add manual arming via LoRa with encrypted transmission
- [ ] Add selftest to all sensors
- [ ] Change "to ned" to "from imu to kpptr"

**This list is work in progress**
